### ISSUE TITLE
Why require the channel name in the POST if the server can only connect to 1 channel?

### ISSUE THREAD

**Issue by dbussert** [hackeriet/irc-http#7]
Reading the docs, the server will only connect to env `IRC_CHANNEL`, but then also makes remote HTTP clients know what that channel name is. Why not name the api endpoint `/channel` and let rest clients always post to that channel?

**Comment by stigok** [comment]
I've corrected the invalid docs, so thanks for the pointing me in that direction. However, this is a long time ago, but it was probably to be able to support multiple channels, which I think makes sense.
